# <namespace>:
#     <variant - e.g. model variant / experiment name>:
#         _overrides: {} # what to override from root configuration 
#       # any specific parameter, e.g. model_options, used in Kedro pipeline
#         model_options: ${merge:${..model_options},${._overrides}}


# # The model_options below are "base" options for all pipelines

model_options:
  model: ""
  test_size: 0.2
  random_seed: 42
  model_config:
    prior_params:

  sampler_config:
    chains: 2
    draws: 2000
    tune: 200 # toDo: 10% of draws
    target_accept: 0.85
    random_seed: 42
  plot_params:
    max_goals: 8
    team_1: 'Augsburg'
    team_2: 'Bochum'

# -------------------------------
# Pipeline-specific configuration


pymc:
  # base:
  #   _overrides:
  #   model_options: ${...model_options}
  
  f1:
    _overrides:
      model: "f1"
      model_config:
        prior_params:
          off_mu: 1.75
          off_tau: 1.0
          def_mu: 0.0
          def_tau: 1.0
    model_options: ${merge:${...model_options},${._overrides}}

  f2:
    _overrides:
      model: "f2"
      model_config:
        prior_params:
          score:
            tau: 1.0
            mu: 0.0
          offence_defence_diff:
            tau: 1.0
            mu: 1.75 #avg/2
          home_advantage:
            tau: 10.0
            mu: 0.0
          weights:
            tau: 100.0
            mu: [0.0, 0.25, -0.25]
    model_options: ${merge:${...model_options},${._overrides}}


pymc2:
  # base:
  #   _overrides:
  #   model_options: ${...model_options}
  
  f1:
    _overrides:
      model: "f1"
      model_config:
        prior_params:
          off_mu: 1.75
          off_tau: 1.0
          def_mu: 0.0
          def_tau: 1.0
    model_options: ${merge:${...model_options},${._overrides}}