# <namespace>:
#     <variant - e.g. model variant / experiment name>:
#         _overrides: {} # what to override from root configuration 
#       # any specific parameter, e.g. model_options, used in Kedro pipeline
#         model_options: ${merge:${..model_options},${._overrides}}


# # The model_options below are "base" options for all pipelines

model_options:
  model: "" 
  engine: ""
  start_day: 20
  walk_forward: 1
  test_size: 0.2
  model_config: #define in model specific config
  sampler_config: #define in model specific config
      random_seed: 42
# -------------------------------
  plot_params:
    max_goals: 8
    team_1: 'Augsburg'
    team_2: 'Bochum'

# -------------------------------
# Pipeline-specific configuration


pymc:
  _overrides_base:
    engine: "pymc"
    model_config:
    sampler_config:
      chains: 2
      draws: 1000
      tune: 100 # toDo: 10% of draws
      target_accept: 0.9

  
  simple:
    _overrides:
      model: "simple"
      model_config:
        prior_params:
          off_mu: 1.75
          off_tau: 1.0
          def_mu: 0.0
          def_tau: 1.0
    model_options: ${merge:${merge:${...model_options},${.._overrides_base}},${._overrides}}

  toto:
    _overrides:
      model: "toto"
      model_config:
        prior_params:
          score:
            tau: 1.0
            mu: 0.0
          offence_defence_diff:
            tau: 1.0
            mu: 1.75 #avg/2
          home_advantage:
            tau: 10.0
            mu: 0.0
          weights:
            tau: 100.0
            mu: [0.0, 0.25, -0.25]
    model_options: ${merge:${merge:${...model_options},${.._overrides_base}},${._overrides}}


pyro:
  _overrides_base:
    engine: "pyro"
    model_config:
      betas: [0.95, 0.999]
      learning_rate: 0.005
      prior_diff: 1.5

  simple:
    _overrides:
      model: "simple"
    model_options: ${merge:${merge:${...model_options},${.._overrides_base}},${._overrides}}

  toto:
    _overrides:
      model: "toto"
    model_options: ${merge:${merge:${...model_options},${.._overrides_base}},${._overrides}}